version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python starter/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgres://postgres@db:5432/postgres'
    volumes:
      - .:/app/code
    ports:
      - "8000:8000"
    depends_on:
      - db
